### ISSUE TITLE
求一下资源

### ISSUE THREAD

**Issue by Wen146237** [DominicLiang/RpgUdemyCourse#1]
那个课程的资源可否求一下呢，qq468342767，麻烦您了

**Comment by DominicLiang** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DominicLiang/RpgUdemyCourse"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月14日(星期五) 下午4:23
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[DominicLiang/RpgUdemyCourse] 求一下资源 (Issue #1)

你直接克隆我这个就有了,里面有所有图片,但是没有音频,音频我也没找到


 
那个课程的资源可否求一下呢，qq468342767，麻烦您了
